### ISSUE TITLE
compile error - vista cygwin

### ISSUE THREAD

**Issue by Ben-401** [MEGA65/m65dbg#10]
also refer to https://groups.google.com/forum/#!topic/c65gs-development/FEVkgRqs8Dg

$ make
gcc -c -Wall -g main.c -o main.o
main.c:7:31: fatal error: readline/readline.h: No such file or directory
compilation terminated.
Makefile:24: recipe for target 'main.o' failed
make: **\* [main.o] Error 1

$ gcc commands.c gs4510.c main.c serial.c
main.c:7:31: fatal error: readline/readline.h: No such file or directory
compilation terminated.
serial.c: In function ‘serialFlush’:
serial.c:118:13: error: ‘FIONREAD’ undeclared (first use in this function)
   ioctl(fd, FIONREAD, &bytes_available);
             ^
serial.c:118:13: note: each undeclared identifier is reported only once for each function it appears in

**Comment by gurcei** [comment]
I believe the readline error will be fixed by re-running cygwin's setup.exe and installing the **libreadline-devel** package.

As for the FIONREAD error, I'll look into that now and try figure out which package it belongs to and get back to you.

**Comment by gurcei** [comment]
The only other mystery left is what package is needed for that "FIONREAD" stuff...

I used grep inside my cygwin's "/usr/include" folder to try locate which include-files refer to this FIONREAD...

I then use a 'cygcheck' tool to figure out which packages those include files referred to.

The tool reports that the likely packages needed are:

**cygwin64**
- I'm guessing this one comes with a default install and you should already have this

**cygwin64-w32api-headers**
- while I don't recall manually installing this package, I'm guessing it got installed on my system due to being a pre-requisite to some other package I installed in the past on my cygwin system.

Anyway, try running cygwin's setup.exe and installing that latter package, and _hopefully_ that FIONREAD error will go away too. If not, let me know and we can investigate it further.

**Comment by apnof** [comment]
Search led me here first; found a solution over at sourceforge. Just wanted to drop a link for the next person who gets stuck with FIONREAD when compiling some C on cygwin:
[Serial Port Programming in C++](https://sourceforge.net/p/libserial/discussion/29399/thread/b753d005/#fe62/7c3b)

Possible solution:
`#ifndef FIONREAD    // cygwin defines FIONREAD in  socket.h  instead of  ioctl.h`
`#include <sys/socket.h>`
`#endif`

**Comment by gurcei** [comment]
Think some solutions have been documented on this ticket, so closing.
